### ISSUE TITLE
Permission to use code in TerrariaChatRelay

### ISSUE THREAD

**Issue by xNarnia** [KindRedSand/TerrariaTwitchChat#1]
Hiiiiii

I found your mod and would love to add your IRCClient code to my mod.
This would help extend the functionality of my mod to also support any IRC client. 
May I have your permission to use your full source code in my mod with credit and attribution to you in the comments of the code?

Edit: Here is a link to the GitHub
https://github.com/xPanini/TCR-TerrariaChatRelay

**Comment by KindRedSand** [comment]
Yes, you can use my code in your mod. It _will_ require some editing since it are hardcoded to twitch IRC server (tag caps and ping responce)  but i hope it will help you with your mod

**Comment by xNarnia** [comment]
Thank you so much!!!!
